### ISSUE TITLE
Need normalization or not for features?

### ISSUE THREAD

**Issue by stuartnankai** [fbrundu/pymrmr#38]
* PymRMR version:
* Python version: 3.6
* Operating System: MacOS

### Description
Hi, Sorry to bother you, your package helps me a lot, I am just wondering that the features (columns ) need to be normalized before the mrmr or not? My project is focus on regression problem not classification. Thank you in advance!

Jian

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by fbrundu** [comment]
Dear Jian,
Please refer to the original publication. You can find all the information here: http://home.penglab.com/proj/mRMR/
The only form of preprocessing you have to use is discretisation of data (e.g. 0 if the value is between +- standard deviation, -1 or 1 otherwise), which is not provided by this module (differently from original code).
The kind of normalisation you can use depend on the type and quality of your data, so I really cannot help here. Please also note that this algorithm focuses on feature selection for *classification*, I am not sure what the result will be for regression.

Thanks,
Francesco
